empty bucket before destroying stack

diff --git a/.github/workflows/infra-deploy.yml b/.github/workflows/infra-deploy.yml
--- a/.github/workflows/infra-deploy.yml
+++ b/.github/workflows/infra-deploy.yml
@@ -1476,7 +1476,7 @@ jobs:
     environment:
       name: aws-infra-${{ needs.run_eligible.outputs.env-ref-name }}
     outputs:
-      failed-reason: ${{ steps.destroying-comment.outputs.failedReason || steps.describe-stack.outputs.failedReason || steps.update-issue-destroy-complete.outputs.failedReason }}
+      failed-reason: ${{ steps.destroying-comment.outputs.failedReason || steps.describe-stack.outputs.failedReason || steps.update-issue-destroy-complete.outputs.failedReason || steps.empty-bucket.outputs.failedReason }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -1590,6 +1590,23 @@ jobs:
           # setup cicd role through instructions from aws-manual branch.
           role-to-assume: ${{ secrets.AWS_CICD_ROLE_ARN }}
           role-session-name: cdkSession
+      - id: empty-bucket
+        name: Empty S3 bucket
+        env:
+          INFRA_ENV: ${{ vars.INFRA_ENV }}
+        run: |
+          RECEIPT_S3_BUCKET="prsfin-$INFRA_ENV-expense-receipt-s3-bucket"
+          echo "deleting all objects from s3 bucket [$RECEIPT_S3_BUCKET] before destroying stack"
+          set +e
+          EMPTY_BUCKET_OUT=$(aws s3 rm s3://$RECEIPT_S3_BUCKET --recursive --only-show-errors)
+          RET_CODE=$?
+          set -e
+          if [[ $RET_CODE -ne 0 || -n $EMPTY_BUCKET_OUT ]]; then
+            FAILED_REASON="There was error emptying bucket. Error: $EMPTY_BUCKET_OUT"
+            echo "failedReason=$FAILED_REASON" >> $GITHUB_OUTPUT
+            echo "failedReason=$FAILED_REASON"
+            exit 1
+          fi
       - name: cdk destroy
         uses: youyo/aws-cdk-github-actions@v2
         with:
