update timezone for audit details to write in issue comment; refactored ui deploy workflow with proper validations

diff --git a/.github/workflows/ui-deploy.yml b/.github/workflows/ui-deploy.yml
--- a/.github/workflows/ui-deploy.yml
+++ b/.github/workflows/ui-deploy.yml
@@ -37,6 +37,7 @@ jobs:
       name: aws-infra-${{ github.event.client_payload.env_type }}
     outputs:
       branch-name: ${{ steps.get-milestone.outputs.branchName }}
+      failed-reason: ${{ steps.payload-schema.outputs.failedReason || steps.get-milestone.outputs.failedReason }}
     steps:
       - name: Env Config
         run: |
@@ -47,17 +48,21 @@ jobs:
             echo "One or more required environment variables are not set."
             exit 1
           fi
-      - name: Payload Schema
+      - id: payload-schema
+        name: Payload Schema
         uses: actions/github-script@v7
         with:
           script: |
             const payload = context.payload.client_payload;
             const errors = [];
-            if(!Array.isArray(payload.stackTags)) {
+            if(!Array.isArray(payload.stack_tags)) {
               errors.push("stack tags is not array.");
             }
             if(payload.type !== "provision" && payload.type !== "deprovision") {
               errors.push("request type is not supported.");
+            }
+            if(!payload.milestone) {
+              errors.push("milestone is not provided");
             }
             if(!payload.ui_repository) {
               errors.push("ui_repository is not provided");
@@ -69,7 +74,9 @@ jobs:
               errors.push("artifact_name is not provided");
             }
             if(errors.length>0) {
-              core.setFailed("client payload schema invalid. errors: [" + errors.join(",") + "]");
+              const failedMessage = "client payload schema invalid. errors: [" + errors.join(",") + "]";
+              core.setOutput("failedReason", failedMessage);
+              core.setFailed(failedMessage);
             }
       - name: Checkout
         uses: actions/checkout@v4
@@ -185,20 +192,42 @@ jobs:
       - name: Validate UI stack status
         env:
           INFRA_ENV: ${{ vars.INFRA_ENV }}
+          MILESTONE_TITLE: ${{ github.event.client_payload.milestone }}
         run: |
-          UI_STACK_NAME="prsfin-$INFRA_ENV-ui-deploy-stack"
           FAILED_REASON=""
+          UI_STACK_NAME="prsfin-$INFRA_ENV-ui-deploy-stack"
           set +e
           DESCRIBE_UI_STACK_OUT=$(aws cloudformation describe-stacks --stack-name "$UI_STACK_NAME")
           RET_CODE=$?
           set -e
-          if [[ $RET_CODE -eq 0 ]]; then
-            STACK_STATUS=$(echo "$DESCRIBE_UI_STACK_OUT" | jq -r ".Stacks[0].StackStatus")
-            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/view-stack-events.html#cfn-console-view-stack-data-resources-status-codes
-            if [[ "$STACK_STATUS" =~ ^(CREATE_IN_PROGRESS|UPDATE_IN_PROGRESS|DELETE_IN_PROGRESS|ROLLBACK_IN_PROGRESS|UPDATE_ROLLBACK_IN_PROGRESS)$ ]]; then
-              echo "UI Stack deployment is in progress. The system can not start deployment."
-              exit 1
-            fi
+          if [[ $RET_CODE -ne 0 ]]; then
+            echo "UI Stack does not exist. given branch for milestone can be deployed."
+            exit 0
+          fi
+          # verify stack status
+          STACK_STATUS=$(echo "$DESCRIBE_UI_STACK_OUT" | jq -r '.Stacks[0].StackStatus')
+          if [[ ! "$STACK_STATUS" =~ _COMPLETE$ ]]; then
+            STACK_STATUS_REASON=$(echo "$DESCRIBE_UI_STACK_OUT" | jq -r '.Stacks[0].StackStatusReason')
+            FAILED_REASON="The system cannot start UI deployment, because the Stack status is not complete, found Status: $STACK_STATUS. The Stack Status Reason: $STACK_STATUS_REASON"
+            echo "failedReason=$FAILED_REASON" >> $GITHUB_OUTPUT
+            echo "Failed Reason: $FAILED_REASON"
+            exit 1
+          fi
+          # environment tag match must never fail
+          TAG_VALUE=$(echo "$DESCRIBE_UI_STACK_OUT" | jq -r '.Stacks[0].Tags[] | select(.Key=="environment").Value')
+          if [[ "$TAG_VALUE" != "$INFRA_ENV" ]]; then
+            FAILED_REASON="Stack is deployed for other environment $TAG_VALUE stack."
+            echo "failedReason=$FAILED_REASON" >> $GITHUB_OUTPUT
+            echo "Failed Reason: $FAILED_REASON"
+            exit 1
+          fi
+          # check milestone 
+          TAG_VALUE=$(echo "$DESCRIBE_UI_STACK_OUT" | jq -r '.Stacks[0].Tags[] | select(.Key=="milestone").Value')
+          if [[ "$TAG_VALUE" != "$MILESTONE_TITLE" ]]; then
+            FAILED_REASON="Other milestone branch is deployed to Test plan environment. Wait for completion of $TAG_VALUE tests."
+            echo "failedReason=$FAILED_REASON" >> $GITHUB_OUTPUT
+            echo "Failed Reason: $FAILED_REASON"
+            exit 1
           fi
 
   diff_stack:
@@ -239,7 +268,7 @@ jobs:
           cdk_args: "MyFinanceUiDeployStack"
         env:
           INFRA_ENV: ${{ vars.INFRA_ENV }}
-          TAGS: ${{ join(github.event.client_payload.stackTags, ',') }}
+          TAGS: ${{ join(github.event.client_payload.stack_tags, ',') }}
 
   wait_infra_deploy:
     name: Wait for Infra Stack deployment
@@ -264,48 +293,47 @@ jobs:
           INFRA_ENV: ${{ vars.INFRA_ENV }}
         run: |
           # Wait duration to execute the command and check status 
-          SLEEP_DURATION=3m
-          TOTAL_WAIT_DURATION=60m
+          SLEEP_DURATION=30 # 30 sec
+          TOTAL_WAIT_DURATION=1800 # 30 min=30*60
           REMAINING_ATTEMPTS=$((TOTAL_WAIT_DURATION / SLEEP_DURATION))
-          WAIT_DURATION_STACK_NOT_EXIST=15m
-          REMAINING_ATTEMPTS_STACK_NOT_EXIST=$((WAIT_DURATION_STACK_NOT_EXIST / SLEEP_DURATION))
           API_STACK_NAME="prsfin-$INFRA_ENV-infra-stack"
-          while :; do
+          echo "initial wait for 5 min, assuming request is submitted for api stack and is getting processed"
+          sleep 300
+          while [[ $REMAINING_ATTEMPTS -gt 0 ]]; do
             echo "Deployment is in progress. Waiting for $SLEEP_DURATION."
             sleep $SLEEP_DURATION
+            REMAINING_ATTEMPTS=$((REMAINING_ATTEMPTS - 1))
             set +e
             DESCRIBE_API_STACK_OUT=$(aws cloudformation describe-stacks --stack-name "$API_STACK_NAME")
             RET_CODE=$?
             set -e
-            if [[ $RET_CODE -eq 0 ]]; then
-              STACK_STATUS=$(echo "$DESCRIBE_API_STACK_OUT" | jq -r ".Stacks[0].StackStatus")
-              # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/view-stack-events.html#cfn-console-view-stack-data-resources-status-codes
-              if [[ "$STACK_STATUS" =~ ^(CREATE_COMPLETE|UPDATE_COMPLETE)$ ]]; then
-                echo "Infra Stack is deployed successfully."
-                break
-              elif [[ "$STACK_STATUS" =~ ^(CREATE_FAILED|UPDATE_FAILED|ROLLBACK.*|UPDATE_ROLLBACK.*|DELETE.*)$ ]]; then
-                FAILED_REASON="Infra Stack deployment failed. Stack status is $STACK_STATUS. Please check stack events."
-                break
-              fi
-            elif [[ $REMAINING_ATTEMPTS_STACK_NOT_EXIST -gt 0 ]]; then
-              REMAINING_ATTEMPTS_STACK_NOT_EXIST=$((REMAINING_ATTEMPTS_STACK_NOT_EXIST - 1))
+            if [[ $RET_CODE -ne 0 ]]; then
+              echo "Describe Stack failed with exit code, $RET_CODE. Will wait more"
+              continue
             fi
-            if [[ $REMAINING_ATTEMPTS -eq 0 ]]; then
-              FAILED_REASON="Infra Stack deployment is taking longer time. Please check the status manually."
+            # verify stack status
+            STACK_STATUS=$(echo "$DESCRIBE_API_STACK_OUT" | jq -r '.Stacks[0].StackStatus')
+            if [[ "$STACK_STATUS" =~ _COMPLETE$ ]]; then
+              echo "Infra Api Stack deployment is complete."
               break
             fi
-            if [[ $REMAINING_ATTEMPTS_STACK_NOT_EXIST -eq 0 ]]; then
-              FAILED_REASON="Infra Stack deployment has not been started. Stack does not exist. Please check API request form and workflow"
-              break
+            if [[ "$STACK_STATUS" =~ ^(CREATE_FAILED|UPDATE_FAILED|ROLLBACK.*|UPDATE_ROLLBACK.*|DELETE.*)$ ]]; then
+              STACK_STATUS_REASON=$(echo "$DESCRIBE_API_STACK_OUT" | jq -r '.Stacks[0].StackStatusReason')
+              FAILED_REASON="Infra Api Stack deployment failed. Stack status is $STACK_STATUS. Stack Reason: $STACK_STATUS_REASON Please check logs for more details."
+              echo "Failed Reason: $FAILED_REASON"
+              exit 1
             fi
-            REMAINING_ATTEMPTS=$((REMAINING_ATTEMPTS - 1))
           done
 
-          if [[ -n "$FAILED_REASON" ]]; then
-            echo "Failed Reason: $FAILED_REASON"
+          if [[ $RET_CODE -ne 0 ]]; then
+            echo "Infra Api Stack deployment is not started."
             exit 1
           fi
-          DISTRIBUTION_ID=$(echo "$DESCRIBE_API_STACK_OUT" | jq -r '.Stacks[0].Outputs[?starts_with(OutputKey,`DistributionId`) == `true`].OutputValue')
+          if [[ ! "$STACK_STATUS" =~ _COMPLETE$ ]]; then
+            echo "Infra Api Stack deployment is taking longer time than expected. please validate stack manually"
+            exit 1
+          fi
+          DISTRIBUTION_ID=$(echo "$DESCRIBE_API_STACK_OUT" | jq -r '.Stacks[0].Outputs[] | select(.OutputKey | starts_with("DistributionId")).OutputValue')
           echo "distribution_id=$DISTRIBUTION_ID" >> $GITHUB_OUTPUT
 
   deployment:
@@ -364,20 +392,23 @@ jobs:
           cdk_args: "--require-approval never --exclusively"
         env:
           INFRA_ENV: ${{ vars.INFRA_ENV }}
-          TAGS: ${{ join(github.event.client_payload.stackTags, ',') }}
-      - run: |
-          echo aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/personal-finance/index.html" --query "Invalidation.Id" --output text
-          INVALIDATION_ID=`aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/personal-finance/index.html" --query "Invalidation.Id" --output text`
-          echo Invalidation Id = $INVALIDATION_ID
-          INVALIDATION_STATUS="inprogress"
-          SLEEP_DURATION=20
-          until [ "$INVALIDATION_STATUS" == "Completed" ]; do
-            echo aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text
-            INVALIDATION_STATUS=`aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text`
-            echo invalidation status = $INVALIDATION_STATUS, sleeping $SLEEP_DURATION sec if inprogress
-            sleep $SLEEP_DURATION
-          done
-          echo The task, to invalidate cache for index.html, is now completed.
+          TAGS: ${{ join(github.event.client_payload.stack_tags, ',') }}
+      - name: Invalidate old UI Cf cache
         env:
           INFRA_ENV: ${{ vars.INFRA_ENV }}
           DISTRIBUTION_ID: ${{ needs.wait_infra_deploy.outputs.distribution-id }}
+          UI_BASE_PATH: ${{ vars.UI_BASE_PATH }}
+        run: |
+          echo aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "$UI_BASE_PATH/index.html" --query "Invalidation.Id" --output text
+          INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "$UI_BASE_PATH/index.html" --query "Invalidation.Id" --output text)
+          echo Invalidation Id = $INVALIDATION_ID
+          INVALIDATION_STATUS="inprogress"
+          SLEEP_DURATION=30
+          until [ "$INVALIDATION_STATUS" == "Completed" ]; do
+            echo "sleeping $SLEEP_DURATION sec since cf cache hasn't been invalidated"
+            sleep $SLEEP_DURATION
+            echo aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text
+            INVALIDATION_STATUS=$(aws cloudfront get-invalidation --id $INVALIDATION_ID --distribution-id $DISTRIBUTION_ID --query "Invalidation.Status" --output text)
+            echo "Invalidation Status: $INVALIDATION_STATUS"
+          done
+          echo "The task, to invalidate cache for index.html, is now completed."
